server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaoyun?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
#      web-stat-filter:
#        exclusions:
#      stat-view-servlet:
#        login-username:
#        login-password: