server:
  port: 8081

spring:
  datasource: # 数据源的相关配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
      url: jdbc:mysql://127.0.0.1:3306/testjy?characterEncoding=utf8
      username: root
      password: root
#      web-stat-filter:
#        exclusions:
#      stat-view-servlet:
#        login-username:
#        login-password: